# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nmah/Desktop/Final_Project/Final_Project.cache/wt [current_project]
set_property parent.project_path C:/Users/nmah/Desktop/Final_Project/Final_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Users/nmah/Desktop/Final_Project/Final_Project.srcs/sources_1/new/Clock_Divider.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Clock_Divider -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Clock_Divider.dcp

catch { report_utilization -file Clock_Divider_utilization_synth.rpt -pb Clock_Divider_utilization_synth.pb }
