# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Nick Mah/Documents/GitHub/Cal-Poly-SLO-CPE-133/Final_Project/Final_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Nick Mah/Documents/GitHub/Cal-Poly-SLO-CPE-133/Final_Project/Final_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Nick Mah/Documents/GitHub/Cal-Poly-SLO-CPE-133/Final_Project/Final_Project.srcs/sources_1/new/Fourier_Register.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Fourier_Register -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Fourier_Register.dcp

catch { report_utilization -file Fourier_Register_utilization_synth.rpt -pb Fourier_Register_utilization_synth.pb }
